git:
 depth: 5

jobs:
 include:
  - stage: "Build and Test Java"
    language: java
    jdk: orclejdk11
    before script:
     - cd sample-application-backend
  - stage: "Build and Test Nodejs"
    language: node.sj
    node js: "12.20"
    before_script:
     - cd sample-application-frontend
cache:
 directories:
  - "$HOME/ .m2/repository"
  - "$HOME/ .npm"