git:
  depth: 5

stages:
  - "Build and Test"
  - "Package"

jobs:
  include:
  - stage: "Build and Test"
    language: java
    jdk: oraclejdk11
    before_script:
      - cd sample-application-backend
    script:
      - echo "Maven build"
      - echo "Run test coverage and Quality Gate"
      - mvn clean verify org.jacoco:jacoco-maven-plugin:prepare-agent install sonar:sonar -Dsonar.projectKey=CorentinBordes-CPE_sample-application-students
  - stage: "Build and Test"
    language: node.js
    node_js: "12.20"
    before_script:
      - cd sample-application-frontend
    script:
      - echo "NPM install and build"
      - npm run
  - stage: "Package"
    before_script:
      - cd sample-application-backend
    script:
      - echo "Docker build ..."
      - docker build -t cbordes98/sample-application-backend .
      - echo "Docker login ..."
      - echo "$DOCKER_PWD_CREDENTIAL" | docker login -u "cbordes98" --password-stdin
      - echo "Docker push ..."
      - docker push cbordes98/sample-application-backend
  - stage: "Package"
    before_script:
      - cd sample-application-frontend
    script:
      - echo "Docker build ..."
      - docker build -t cbordes98/sample-application-frontend .
      - echo "Docker login ..."
      - echo "$DOCKER_PWD_CREDENTIAL" | docker login -u "cbordes98" --password-stdin
      - echo "Docker push ..."
      - docker push cbordes98/sample-application-frontend

cache:
  directories:
    - "$HOME/.m2/repository"
    - "$HOME/.npm"
services:
    - docker
addons:
  sonarcloud:
    organization: "corentinbordes-cpe"
    token: "$SONAR_TOKEN"

