all:
 vars:
  ansible_user: centos
  ansible_ssh_private_key_file: "C:\Users\Corentin BORDES\Desktop\CoursCPE\DevOps\TP3\sample-application-students\ansible\crypted_id_rsa"
 children:
  prod:
   hosts: corentin.bordes.takima.cloud